# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
