# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('additional_notes', models.TextField(null=True)),
            ],
        ),
    ]
