# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_item', '0001_initial'),
        ('item_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='menu_item.MenuItem'),
        ),
    ]
