# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='given_name',
            new_name='owner_given_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='owner_surname',
        ),
    ]
