# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170819_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='additional_notes',
            field=models.TextField(null=True),
        ),
    ]
