# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='created_on',
            new_name='added_on',
        ),
    ]
