# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170813_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('additional_notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='api.MenuItem'),
        ),
    ]
