# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170812_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
